extends RefCounted

## What a butterfly LOOKS like while it stands on a bloom and drinks.
##
## ## The bug this exists for
##
## Reported twice: "butterflies get stuck in front of a single flower". The
## forage RULE was measured exhaustively and cleared -- a butterfly visits
## 20-29 DISTINCT blooms per 600 simulated seconds, longest loiter 6.8-11.5s.
## The plan was fine. What was wrong was the PICTURE. For the whole of
## PollinatorForaging.DRINK_SECONDS the marker snapped onto an exact pixel
## (`position = _forage_target`), never touched `position` again, and kept
## running the FLIGHT flap -- because `perched_frame` is generated by
## ProceduralBirdSprite alone, so a butterfly had no settled frame and fell
## straight through to `flap_frames`. Net visual: a butterfly HOVERING, wings
## beating, motionless on one pixel, for 2.4 seconds, over and over. That is
## exactly what "stuck IN FRONT OF a flower" describes -- in front of, not on.
##
## ## What a real butterfly does instead
##
## - Monarchs, swallowtails and blue morphos PERCH to feed. Hovering while
##   nectaring is a hawkmoth trait, not a butterfly one.
## - The feeding wing posture is nothing like flight: the wings are held
##   closed over the back and opened only slowly and occasionally (basking,
##   haemolymph pumping) -- SECONDS per cycle, not several beats a second.
## - They shuffle around the flower head constantly, working different florets
##   with the proboscis. A feeding butterfly is never motionless for 2.4 s.
##
## Pure functions and constants, no nodes, engine-free -- the same shape as
## FlapGlide, WingbeatBounce and FlightIrregularity, which own the other three
## things a flyer's body does.

const FlightIrregularity = preload("res://src/gameplay/flight_irregularity.gd")
const PollinatorForaging = preload("res://src/gameplay/pollinator_foraging.gd")
## The alighting below was the first thing in this game to derive a transition
## duration from the flyer's own airspeed instead of picking one. It turned out
## not to be only about nectaring -- every other state entry in
## AmbientFlyerMarker needed the same idea with a different gap -- so the two
## functions at the bottom of this file are now the LANDING_DISTANCE
## specialisation of FlightTransition rather than a second implementation of it.
const FlightTransition = preload("res://src/rendering/flight_transition.gd")


## How long one full shut -> open -> shut of the wings takes, in seconds.
##
## Grounded in real seconds rather than as a multiple of the flight beat: a
## nectaring butterfly's wings open and close on the order of once every few
## seconds. Deliberately LONGER than PollinatorForaging.DRINK_SECONDS (2.4 s),
## so that within a single stop the wings open at most ONCE -- "occasionally",
## which is what basking is, rather than a slow rhythm anyone could count.
## Pinned by test_the_wings_open_at_most_once_during_a_single_drink and by
## test_the_settled_cycle_is_an_order_of_magnitude_slower_than_the_flight_beat.
const SECONDS_PER_CYCLE := 4.0

## How long the wings take to swing open (and, separately, to swing shut).
##
## About half a second each way, which is what a basking wing visibly does --
## fast enough to be a movement rather than a morph, slow enough that it is
## never mistaken for a beat. This is the number the shut duty below is
## DERIVED from, so there is exactly one free parameter here rather than two
## that can drift apart.
const OPENING_SECONDS := 0.6

## How far a feeding insect shuffles around the bloom, as a fraction of its
## own drawn body length.
##
## A butterfly working a flower head walks around the head, probing different
## florets. The excursion is therefore the size of the FLOWER HEAD: a
## composite head (aster, clover, thistle, a milkweed umbel) is roughly 20 mm
## across, so about 10 mm of reach from its centre, against a monarch's
## roughly 27 mm body.
##
## Expressed as that RATIO and read against the DRAWN body rather than in
## metres through GroundSlide.PX_PER_METER, because ambient flyers are drawn
## far larger than life: PX_PER_METER makes a real 100 mm monarch wingspan
## 1.3 world px, where the sprite is drawn about 3.9 px across. Metres would
## give a sub-pixel shuffle nobody could see; the ratio is what actually keeps
## it reading as "shuffling ON this bloom". Same reasoning, and the same
## texture-height yardstick, as WingbeatBounce's amplitude.
const FLORET_SHUFFLE_BODY_FRACTION := 10.0 / 27.0

## Decorrelates the two irregularity reads below, so the bearing this insect
## walks and how far out it walks are not the same wave twice. A salt on the
## seed rather than a second noise source -- FlightIrregularity is the one
## place this game says "a butterfly's path never repeats the same arc twice",
## and a second wobble beside it would be that statement made twice with two
## sets of numbers to keep in step.
const _SHUFFLE_RADIUS_SALT := 7919

## The shuffle runs on the SETTLED clock, not the flight one.
##
## FlightIrregularity is a FLYING insect's wobble: its fast component turns at
## FAST_RADIANS_PER_SECOND, about one veer a second, which is what a butterfly
## crossing a meadow does. Read at that rate against a flower head's radius, the
## floret shuffle carried a real drawn monarch 0.338 px per frame -- against the
## 0.267 px its own airspeed carries it. A butterfly STANDING on a flower was
## outrunning a butterfly in flight, and on screen that is a vibration rather
## than an insect working a bloom.
##
## A nectaring insect does everything on the order of seconds, which is exactly
## what SECONDS_PER_CYCLE already says about its wings. So the shuffle is read
## on that clock instead: one period of the flight wobble becomes one nectaring
## cycle. Derived from the two constants that already exist, which is why there
## is no walking speed here to tune.
const SHUFFLE_TIME_SCALE := (
	(TAU / FlightIrregularity.FAST_RADIANS_PER_SECOND) / SECONDS_PER_CYCLE
)


func _init() -> void:
	pass


## The fraction of a cycle the wings simply stay shut. Derived from
## OPENING_SECONDS: everything that is not the open-and-shut swing is dwell.
static func closed_duty() -> float:
	if SECONDS_PER_CYCLE <= 0.0:
		return 0.0
	return clampf(1.0 - 2.0 * OPENING_SECONDS / SECONDS_PER_CYCLE, 0.0, 1.0)


## How far open this individual's wings are at `elapsed_seconds`: 0 shut over
## the back, 1 fully open (basking). Zero for most of the cycle, then one
## smooth swing open and shut.
static func openness_fraction(elapsed_seconds: float, seed_value: int) -> float:
	if SECONDS_PER_CYCLE <= 0.0:
		return 0.0
	# Per-individual phase, so two butterflies on neighbouring blooms do not
	# bask in unison -- the same hash-derived phase every other flyer
	# behaviour here uses, never RNG state.
	var own := FlightIrregularity.phase(seed_value) / TAU
	var phase := fposmod(elapsed_seconds / SECONDS_PER_CYCLE + own, 1.0)
	var duty := closed_duty()
	if phase < duty:
		return 0.0
	var span := 1.0 - duty
	if span <= 0.0:
		return 0.0
	# A half-sine over the swing rather than a triangle: a wing that changes
	# direction with a corner in it reads as a snap at the extremes, which is
	# the very thing that makes the flight flap look wrong here.
	return sin(PI * (phase - duty) / span)


## Where in the cycle this individual's wings are fully open -- the top of the
## basking swing -- as seconds from the start of the cycle.
##
## Exists so a LANDING can begin there. A butterfly alights on a flower with
## its wings spread and folds them afterwards; the settled cycle used to be
## read off wall time, so an insect that had just been beating its wings in
## flight was usually drawn fully shut on the very next frame. Starting the
## cycle at the open peak makes the landing play the fold it actually does, and
## it costs nothing: the swing, the phase and the duty are all already here.
static func seconds_to_open(seed_value: int) -> float:
	var own := FlightIrregularity.phase(seed_value) / TAU
	var duty := closed_duty()
	var peak := duty + 0.5 * (1.0 - duty)
	return fposmod(peak - own, 1.0) * SECONDS_PER_CYCLE


## Which of `frame_count` settled frames to show, where frame 0 is the fully
## shut pose and the last is fully open (see
## ProceduralButterflySprite.generate_settled_textures).
static func frame_index(elapsed_seconds: float, frame_count: int, seed_value: int) -> int:
	if frame_count <= 1:
		return 0
	var openness := openness_fraction(elapsed_seconds, seed_value)
	return clampi(int(round(openness * float(frame_count - 1))), 0, frame_count - 1)


## How far, in world pixels, this insect may wander from the bloom's centre
## while it works it -- the flower head's own radius, in the drawn body's
## units (see FLORET_SHUFFLE_BODY_FRACTION).
static func shuffle_reach_px(body_px: float) -> float:
	return maxf(body_px, 0.0) * FLORET_SHUFFLE_BODY_FRACTION


## The insect's offset from the bloom's centre at `elapsed_seconds`, bounded
## by shuffle_reach_px.
##
## An OFFSET FROM A FIXED ANCHOR, never an accumulating step -- that is the
## whole reason it cannot turn into drift, and why it cannot defeat the forage
## rule's arrival detection however long the flyer stands there.
static func shuffle_offset(elapsed_seconds: float, body_px: float, seed_value: int) -> Vector2:
	var reach := shuffle_reach_px(body_px)
	if reach <= 0.0:
		return Vector2.ZERO
	# On the SETTLED clock, not the flight one -- see SHUFFLE_TIME_SCALE.
	var walked := elapsed_seconds * SHUFFLE_TIME_SCALE
	# Read as a BEARING and a RADIUS rather than as x and y, so the result is
	# bounded by `reach` exactly (two independent axes would reach
	# sqrt(2) x reach at the corners) and so it reads as walking AROUND the
	# head rather than as sliding along a diagonal.
	var bearing := FlightIrregularity.wobble(walked, seed_value) * PI
	var radius := (
		0.5
		* (1.0 + FlightIrregularity.wobble(walked, seed_value ^ _SHUFFLE_RADIUS_SALT))
		* reach
	)
	return Vector2.from_angle(bearing) * radius


## The fastest that walk can carry the insect, in world pixels per second.
##
## Bounded rather than sampled, and derived rather than measured: the offset is
## a bearing swung over +/-PI and a radius swung over the reach, both driven by
## FlightIrregularity, so the worst case is the sum of the tangential term
## (radius x bearing rate, at most `reach` x PI x the wobble's own max rate)
## and the radial one (half the reach x that same rate) -- on the settled clock.
##
## Exists so the ALIGHTING can be sized against what is left of the flyer's
## airspeed once the walk it fades in has taken its share, rather than
## spending the whole budget on the approach and then adding a walk on top
## (which is exactly how a butterfly ended up moving 0.469 px on a frame that
## carries it 0.267).
static func shuffle_peak_px_per_second(body_px: float) -> float:
	return (
		shuffle_reach_px(body_px)
		* (PI + 0.5)
		* FlightIrregularity.max_rate()
		* SHUFFLE_TIME_SCALE
	)


## How long the alighting takes, in seconds: as long as it takes this flyer, at
## its own airspeed, to cover the LANDING_DISTANCE gap it still had when the
## forage rule declared it arrived. Derived rather than picked, so a bee
## (faster) sets down quicker than a monarch without a second tuned number
## having to exist.
##
## This used to be that gap over that airspeed exactly, and that was half a
## right answer: it is the AVERAGE rate, and the settle is smoothstepped, so
## the insect was flying FlightTransition.EASE_PEAK_RATE times its own airspeed
## halfway through the very move that exists to stop it teleporting -- 0.467 px
## on a frame that carries it 0.267, measured. settling_seconds pays for the
## ease by stretching the crossing, so the PEAK is the airspeed rather than the
## mean.
##
## `body_px` is this individual as actually drawn, and it is here because the
## settle does not only close the LANDING_DISTANCE gap -- it also fades the
## floret shuffle in (see AmbientFlyerMarker._step_nectaring). So the distance
## crossed is that gap PLUS the shuffle's reach, and the speed available for
## crossing it is the airspeed LESS what the walk itself is already using
## (shuffle_peak_px_per_second). Both are derived; between them they are what
## makes the whole alighting, walk included, fit inside one airspeed instead of
## spending the budget twice. Left at zero for a caller that has no drawn body
## to measure, which then simply gets the bare last-gap settle.
static func alighting_seconds(airspeed_px_per_second: float, body_px: float = 0.0) -> float:
	var spare := airspeed_px_per_second - shuffle_peak_px_per_second(body_px)
	if spare <= 0.0:
		return 0.0
	return FlightTransition.settling_seconds(
		PollinatorForaging.LANDING_DISTANCE + shuffle_reach_px(body_px), spare
	)


## How far through the settle it is: 0 the instant it touched down, 1 once it
## is standing on the bloom. Smoothstepped, so it eases onto the flower
## instead of arriving at full speed and stopping dead.
static func alighting_ease(seconds_since_touchdown: float, settle_seconds: float) -> float:
	return FlightTransition.eased_progress(seconds_since_touchdown, settle_seconds)
