extends RefCounted

## What a butterfly LOOKS like while it stands on a bloom and drinks.
##
## ## The bug this exists for
##
## Reported twice: "butterflies get stuck in front of a single flower". The
## forage RULE was measured exhaustively and cleared -- a butterfly visits
## 20-29 DISTINCT blooms per 600 simulated seconds, longest loiter 6.8-11.5s.
## The plan was fine. What was wrong was the PICTURE. For the whole of
## PollinatorForaging.DRINK_SECONDS the marker snapped onto an exact pixel
## (`position = _forage_target`), never touched `position` again, and kept
## running the FLIGHT flap -- because `perched_frame` is generated by
## ProceduralBirdSprite alone, so a butterfly had no settled frame and fell
## straight through to `flap_frames`. Net visual: a butterfly HOVERING, wings
## beating, motionless on one pixel, for 2.4 seconds, over and over. That is
## exactly what "stuck IN FRONT OF a flower" describes -- in front of, not on.
##
## ## What a real butterfly does instead
##
## - Monarchs, swallowtails and blue morphos PERCH to feed. Hovering while
##   nectaring is a hawkmoth trait, not a butterfly one.
## - The feeding wing posture is nothing like flight: the wings are held
##   closed over the back and opened only slowly and occasionally (basking,
##   haemolymph pumping) -- SECONDS per cycle, not several beats a second.
## - They shuffle around the flower head constantly, working different florets
##   with the proboscis. A feeding butterfly is never motionless for 2.4 s.
##
## Pure functions and constants, no nodes, engine-free -- the same shape as
## FlapGlide, WingbeatBounce and FlightIrregularity, which own the other three
## things a flyer's body does.

const FlightIrregularity = preload("res://src/gameplay/flight_irregularity.gd")
const PollinatorForaging = preload("res://src/gameplay/pollinator_foraging.gd")


## How long one full shut -> open -> shut of the wings takes, in seconds.
##
## Grounded in real seconds rather than as a multiple of the flight beat: a
## nectaring butterfly's wings open and close on the order of once every few
## seconds. Deliberately LONGER than PollinatorForaging.DRINK_SECONDS (2.4 s),
## so that within a single stop the wings open at most ONCE -- "occasionally",
## which is what basking is, rather than a slow rhythm anyone could count.
## Pinned by test_the_wings_open_at_most_once_during_a_single_drink and by
## test_the_settled_cycle_is_an_order_of_magnitude_slower_than_the_flight_beat.
const SECONDS_PER_CYCLE := 4.0

## How long the wings take to swing open (and, separately, to swing shut).
##
## About half a second each way, which is what a basking wing visibly does --
## fast enough to be a movement rather than a morph, slow enough that it is
## never mistaken for a beat. This is the number the shut duty below is
## DERIVED from, so there is exactly one free parameter here rather than two
## that can drift apart.
const OPENING_SECONDS := 0.6

## How far a feeding insect shuffles around the bloom, as a fraction of its
## own drawn body length.
##
## A butterfly working a flower head walks around the head, probing different
## florets. The excursion is therefore the size of the FLOWER HEAD: a
## composite head (aster, clover, thistle, a milkweed umbel) is roughly 20 mm
## across, so about 10 mm of reach from its centre, against a monarch's
## roughly 27 mm body.
##
## Expressed as that RATIO and read against the DRAWN body rather than in
## metres through GroundSlide.PX_PER_METER, because ambient flyers are drawn
## far larger than life: PX_PER_METER makes a real 100 mm monarch wingspan
## 1.3 world px, where the sprite is drawn about 3.9 px across. Metres would
## give a sub-pixel shuffle nobody could see; the ratio is what actually keeps
## it reading as "shuffling ON this bloom". Same reasoning, and the same
## texture-height yardstick, as WingbeatBounce's amplitude.
const FLORET_SHUFFLE_BODY_FRACTION := 10.0 / 27.0

## Decorrelates the two irregularity reads below, so the bearing this insect
## walks and how far out it walks are not the same wave twice. A salt on the
## seed rather than a second noise source -- FlightIrregularity is the one
## place this game says "a butterfly's path never repeats the same arc twice",
## and a second wobble beside it would be that statement made twice with two
## sets of numbers to keep in step.
const _SHUFFLE_RADIUS_SALT := 7919


func _init() -> void:
	pass


## The fraction of a cycle the wings simply stay shut. Derived from
## OPENING_SECONDS: everything that is not the open-and-shut swing is dwell.
static func closed_duty() -> float:
	if SECONDS_PER_CYCLE <= 0.0:
		return 0.0
	return clampf(1.0 - 2.0 * OPENING_SECONDS / SECONDS_PER_CYCLE, 0.0, 1.0)


## How far open this individual's wings are at `elapsed_seconds`: 0 shut over
## the back, 1 fully open (basking). Zero for most of the cycle, then one
## smooth swing open and shut.
static func openness_fraction(elapsed_seconds: float, seed_value: int) -> float:
	if SECONDS_PER_CYCLE <= 0.0:
		return 0.0
	# Per-individual phase, so two butterflies on neighbouring blooms do not
	# bask in unison -- the same hash-derived phase every other flyer
	# behaviour here uses, never RNG state.
	var own := FlightIrregularity.phase(seed_value) / TAU
	var phase := fposmod(elapsed_seconds / SECONDS_PER_CYCLE + own, 1.0)
	var duty := closed_duty()
	if phase < duty:
		return 0.0
	var span := 1.0 - duty
	if span <= 0.0:
		return 0.0
	# A half-sine over the swing rather than a triangle: a wing that changes
	# direction with a corner in it reads as a snap at the extremes, which is
	# the very thing that makes the flight flap look wrong here.
	return sin(PI * (phase - duty) / span)


## Which of `frame_count` settled frames to show, where frame 0 is the fully
## shut pose and the last is fully open (see
## ProceduralButterflySprite.generate_settled_textures).
static func frame_index(elapsed_seconds: float, frame_count: int, seed_value: int) -> int:
	if frame_count <= 1:
		return 0
	var openness := openness_fraction(elapsed_seconds, seed_value)
	return clampi(int(round(openness * float(frame_count - 1))), 0, frame_count - 1)


## How far, in world pixels, this insect may wander from the bloom's centre
## while it works it -- the flower head's own radius, in the drawn body's
## units (see FLORET_SHUFFLE_BODY_FRACTION).
static func shuffle_reach_px(body_px: float) -> float:
	return maxf(body_px, 0.0) * FLORET_SHUFFLE_BODY_FRACTION


## The insect's offset from the bloom's centre at `elapsed_seconds`, bounded
## by shuffle_reach_px.
##
## An OFFSET FROM A FIXED ANCHOR, never an accumulating step -- that is the
## whole reason it cannot turn into drift, and why it cannot defeat the forage
## rule's arrival detection however long the flyer stands there.
static func shuffle_offset(elapsed_seconds: float, body_px: float, seed_value: int) -> Vector2:
	var reach := shuffle_reach_px(body_px)
	if reach <= 0.0:
		return Vector2.ZERO
	# Read as a BEARING and a RADIUS rather than as x and y, so the result is
	# bounded by `reach` exactly (two independent axes would reach
	# sqrt(2) x reach at the corners) and so it reads as walking AROUND the
	# head rather than as sliding along a diagonal.
	var bearing := FlightIrregularity.wobble(elapsed_seconds, seed_value) * PI
	var radius := (
		0.5
		* (1.0 + FlightIrregularity.wobble(elapsed_seconds, seed_value ^ _SHUFFLE_RADIUS_SALT))
		* reach
	)
	return Vector2.from_angle(bearing) * radius


## How long the alighting takes, in seconds: exactly as long as it takes this
## flyer, at its own airspeed, to cover the LANDING_DISTANCE gap it still had
## when the forage rule declared it arrived. Derived rather than picked, so a
## bee (faster) sets down quicker than a monarch without a second tuned number
## having to exist.
static func alighting_seconds(airspeed_px_per_second: float) -> float:
	if airspeed_px_per_second <= 0.0:
		return 0.0
	return PollinatorForaging.LANDING_DISTANCE / airspeed_px_per_second


## How far through the settle it is: 0 the instant it touched down, 1 once it
## is standing on the bloom. Smoothstepped, so it eases onto the flower
## instead of arriving at full speed and stopping dead.
static func alighting_ease(seconds_since_touchdown: float, settle_seconds: float) -> float:
	if settle_seconds <= 0.0:
		return 1.0
	var t := clampf(seconds_since_touchdown / settle_seconds, 0.0, 1.0)
	return t * t * (3.0 - 2.0 * t)
